singleuser:
  extraEnv:
    DB_HOSTNAME: ${db_hostname}
    DB_USERNAME: ${db_username}
    DB_PASSWORD: ${db_password}
    DB_DATABASE: ${db_name}
    # can access public s3 bucket without providing role permission
    AWS_DEFAULT_REGION: ${region}
    AWS_NO_SIGN_REQUEST: "YES"
    AWS_S3_ENDPOINT: "s3.${region}.amazonaws.com"
hub:
  config:
    Authenticator:
      enable_auth_state: true
    CryptKeeper:
      keys:
        - ${auth_state_cryptoKey}
    JupyterHub:
      authenticator_class: generic-oauth
    GenericOAuthenticator:
      client_id: ${jhub_auth_client_id}
      client_secret: ${jhub_auth_client_secret}
      login_service: cognito
      oauth_callback_url: https://${sandbox_host_name}/oauth_callback
      authorize_url: https://${jhub_userpool_domain}.auth.${cognito_region}.amazoncognito.com/oauth2/authorize
      token_url: https://${jhub_userpool_domain}.auth.${cognito_region}.amazoncognito.com/oauth2/token
      userdata_url: https://${jhub_userpool_domain}.auth.${cognito_region}.amazoncognito.com/oauth2/userInfo
      username_key: username
  extraEnv:
    - name: COGNITO_REGION
      value: ${cognito_region}
    - name: JUPYTERHUB_USERPOOL_ID
      value: ${jhub_userpool_id}
    - name: DB_HOSTNAME
      value: ${db_hostname}
    - name: DB_USERNAME
      value: ${db_username}
    - name: DB_PASSWORD
      value: ${db_password}
    - name: DB_DATABASE
      value: ${db_name}
  cookieSecret: ${hub_cookieSecret}

proxy:
  secretToken: ${proxy_secretToken}

ingress:
  hosts:
    - ${sandbox_host_name}
