rbac:
  create: true
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: ${service_account_arn}
autoDiscovery:
  clusterName: ${cluster_name}
cloudProvider: aws
awsRegion: ${region}
