## Deploy environment label, e.g. dev, test, prod
##
global:
  deployEnv: ${environment}
efsProvisioner:
  # If specified, use this DNS or IP to connect the EFS
  dnsName: ${dnsName}
  efsFileSystemId: ${efsFileSystemId}
  awsRegion: ${awsRegion}
  path: ${path}
rbac:
  create: true
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ${service_account_arn}
