#  https://github.com/bitnami/charts/tree/master/bitnami/external-dns#to-300
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "${service_account_arn}"
provider: aws
aws:
  zoneType: public
txtOwnerId: ${hosted_zone_id}
txtPrefix: "${cluster_name}-"
domainFilters:
  - ${domain_name}
policy: sync
registry: txt
